spring:
    application:
        name: cartapi
        
server:
    port: 7070
    context-path: /cartapi
    
datasource:
    url: jdbc:h2:~/pismotest
    username: test
    password: 1234
    
productapi:
    host: localhost
    port: 8080
    app: productapi